name: Suggest a tutorial or example for an existing awesome-gee-catalog dataset
description: This template can be submit a code example to an existing dataset in the catalog
title: "[Dataset Title/Name]:"
labels: ["tutorial"]
assignees:
  - samapriya
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to contribute out this example
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: Dataset-URL
    attributes:
      label: Provide Dataset Link
      description: Provide a link to the existing dataset page ex. https://gee-community-catalog.org/projects/geomorpho90/
    validations:
      required: true
  - type: textarea
    id: Clear_and_concise_description_about_the_example
    attributes:
      label: Describe the example
      description: Add the code example as javascript snippet or the code link
      value: "Add the code example"
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://gee-community-catalog.org/code_of_conduct/)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
